project2:
  target: local
  outputs:
    dev:
      type: snowflake
      account: wx85682.ap-southeast-2
      database: PROJECT2
      warehouse: ETL
      user: dbt
      password: ddbt
      role: DBT_RW
      schema: RAW
      threads: 1
    local:
      type: postgres
      host: dec-db-2.c3ran0wqciga.ap-southeast-2.rds.amazonaws.com
      user: postgres
      password: BYhEJDJ5HCn2KTQOlpJJ
      port: 5432
      threads: 4
      dbname: project2
      schema: raw