project2:
  target: prod
  outputs:
    prod:
      type: snowflake
      account: "{{ env_var('DBT_ENV_SECRET_ACCOUNT') }}"
      database: "{{ env_var('DBT_ENV_SECRET_DATABASE') }}"
      warehouse: "{{ env_var('DBT_ENV_SECRET_WAREHOUSE') }}"
      user: "{{ env_var('DBT_ENV_SECRET_USER') }}"
      password: "{{ env_var('DBT_ENV_SECRET_PASSWORD') }}"
      role: "{{ env_var('DBT_ENV_SECRET_ROLE') }}"
      schema: "{{ env_var('DBT_ENV_SECRET_SCHEMA') }}"
      threads: 1
    local:
      type: postgres
      host: 
      user: 
      password: 
      port: 
      threads: 4
      dbname: 
      schema: 